<?xml version="1.0" encoding="utf-8"?><Database Name="UrlShotnerDB" Class="UrlsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=UrlShotnerDB;Integrated Security=True" SettingsObjectName="UrlShortner.Data.Properties.Settings" SettingsPropertyName="UrlShotnerDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Urls" Member="Urls">
    <Type Name="Url">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RealUrl" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ShortUrl" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TimesUsed" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="User_Url" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordHash" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordSalt" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Association Name="User_Url" Member="Urls" ThisKey="Id" OtherKey="UserId" Type="Url" />
    </Type>
  </Table>
</Database>